model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 32

exp_params:
  dataset: sewer
  data: "/home/markpp/datasets/sewer/"
  image_size: 64
  batch_size: 128 # Better to have a square number
  LR: 0.0002
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 20
  n_workers: 12

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
