model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 128
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000

exp_params:
  dataset: sewer
  data: "/home/markpp/datasets/sewer/"
  image_size: 64
  batch_size: 128 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 50
  n_workers: 12

logging_params:
  save_dir: "logs/"
  name: "BetaVAE_B"
  manual_seed: 1265
