model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 32

exp_params:
  dataset: teejet
  data_path: "data/"
  train_list: "/home/markpp/datasets/teejet/iphone_data/train.txt"
  val_list: "/home/markpp/datasets/teejet/iphone_data/val.txt"
  img_size: 64
  batch_size: 48 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30
  n_workers: 8

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
