model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 32

exp_params:
  dataset: teejet
  data_path: "data/"
  train_list: "/home/markpp/datasets/harbour_frames/2/view1_train.txt"
  val_list: "/home/markpp/datasets/harbour_frames/2/view1_val.txt"
  img_size: 512
  batch_size: 64 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 10
  n_workers: 8

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
